# Generated by Django 2.2.4 on 2019-08-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lil_jstor', '0003_coloringbook_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.PositiveSmallIntegerField(blank=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
