# Generated by Django 2.2.4 on 2019-08-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lil_jstor', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='coloring_book_id',
            field=models.PositiveSmallIntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
