# Generated by Django 2.2.4 on 2019-08-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lil_jstor', '0005_comment_coloring_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='add_date',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
