# Generated by Django 2.2.4 on 2019-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lil_jstor', '0006_auto_20190819_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringbook',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'no rating'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
    ]
